import type { Metadata } from "next";
import "./globals.css";
import ScrollToTop from "@/components/ScrollToTop";



export const metadata: Metadata = {
  title: "مسار التغذية تجمع جازان",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ar"
      dir="rtl"

    >
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Almarai:wght@400;700;800&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-almarai bg-gray-50 text-gray-900 antialiased">
      <ScrollToTop/>
        {children}
      </body>
    </html>
  );
}
